name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: connect to server via ssh and deploy
      run: |
        ssh -p 22 siralex@${{ secrets.SSH_HOST }} '
            cd /chemin/vers/votre/projet &&
            echo "toto"
            # git pull &&
            # docker-compose up -d
          '
